function(join_paths joined_path first_path_segment)
  set(temp_path "${first_path_segment}")
  foreach(current_segment IN LISTS ARGN)
    if(NOT current_segment STREQUAL "")
      string(REGEX REPLACE "/+$" "" temp_path "${temp_path}")
      string(REGEX REPLACE "^/+" "" current_segment "${current_segment}")
      set(temp_path "${temp_path}/${current_segment}")
    endif()
  endforeach()
  set(${joined_path} "${temp_path}" PARENT_SCOPE)
endfunction()
